<a href="https://colab.research.google.com/github/deeeplearning-fr/scikit-learn/blob/main/Formation_Scikit_Learn_Cheat_Sheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## A Basic Example

In [ ]:
from sklearn import neighbors, datasets, preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

iris = datasets.load_iris()
X, y = iris.data[:, :2], iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=33)

scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

knn = neighbors.KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)
accuracy_score(y_test, y_pred)

0.631578947368421

## Loading The Data
Your data needs to be numeric and stored as NumPy arrays or SciPy sparse matrices. Other types that are convertible to numeric arrays, such as Pandas DataFrame, are also acceptable.

In [ ]:
from sklearn import datasets

iris = datasets.load_iris()
# print(iris)
X, y = iris.data, iris.target


# Split Data Training And Test Data : sklearn.model_selection

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=33)

# Preprocessing The Data : sklearn.preprocessing

### Standardization
Standardize features by removing the mean and scaling to unit variance
z = (x - u) / s

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler().fit(X_train)
standardized_X = scaler.transform(X_train)
standardized_X_test = scaler.transform(X_test)
standardized_X[:3]

array([[-0.91090798, -1.59775374, -0.15379535, -0.14784433],
       [-1.0271058 ,  0.08448757, -1.15396123, -1.2248242 ],
       [ 0.59966379, -1.59775374,  0.45741713,  0.25602312]])

### Normalization

In [ ]:
from sklearn.preprocessing import Normalizer

scaler = Normalizer().fit(X_train)
normalized_X = scaler.transform(X_train)
normalized_X_test = scaler.transform(X_test)

### Binarization

In [ ]:
from sklearn.preprocessing import Binarizer

binarizer = Binarizer(threshold=0.0).fit(X)
binary_X = binarizer.transform(X)

### Encoding Categorical Features

In [ ]:
from sklearn.preprocessing import LabelEncoder

enc = LabelEncoder()
y = enc.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### Imputing Missing Values

In [ ]:
from sklearn.impute import SimpleImputer

imp = SimpleImputer(missing_values=0, strategy='mean')
imp.fit_transform(X_train)

array([[5. , 2.3, 3.3, 1. ],
       [4.9, 3.1, 1.5, 0.2],
       [6.3, 2.3, 4.4, 1.3],
       [5.8, 2.6, 4. , 1.2],
       [6.2, 2.9, 4.3, 1.3],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [5.1, 2.5, 3. , 1.1],
       [4.8, 3.4, 1.6, 0.2],
       [7.9, 3.8, 6.4, 2. ],
       [5.1, 3.4, 1.5, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.5, 3. , 5.5, 1.8],
       [5.4, 3.9, 1.7, 0.4],
       [7. , 3.2, 4.7, 1.4],
       [5.8, 2.8, 5.1, 2.4],
       [7.7, 2.6, 6.9, 2.3],
       [5.5, 2.5, 4. , 1.3],
       [5.9, 3.2, 4.8, 1.8],
       [4.9, 3.6, 1.4, 0.1],
       [4.5, 2.3, 1.3, 0.3],
       [6.3, 2.8, 5.1, 1.5],
       [4.4, 2.9, 1.4, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [7.2, 3. , 5.8, 1.6],
       [6. , 3.4, 4.5, 1.6],
       [6.2, 2.2, 4.5, 1.5],
       [7.4, 2.8, 6.1, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [6.4, 2.8, 5.6, 2.2],
       [5.7, 2.5, 5. , 2. ],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.5, 0.3],
       [6.8, 2

### Generating Polynomial Features

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(5)
poly.fit_transform(X)

array([[1.0000000e+00, 5.1000000e+00, 3.5000000e+00, ..., 1.5680000e-02,
        2.2400000e-03, 3.2000000e-04],
       [1.0000000e+00, 4.9000000e+00, 3.0000000e+00, ..., 1.5680000e-02,
        2.2400000e-03, 3.2000000e-04],
       [1.0000000e+00, 4.7000000e+00, 3.2000000e+00, ..., 1.3520000e-02,
        2.0800000e-03, 3.2000000e-04],
       ...,
       [1.0000000e+00, 6.5000000e+00, 3.0000000e+00, ..., 2.1632000e+02,
        8.3200000e+01, 3.2000000e+01],
       [1.0000000e+00, 6.2000000e+00, 3.4000000e+00, ..., 3.5478972e+02,
        1.5111414e+02, 6.4363430e+01],
       [1.0000000e+00, 5.9000000e+00, 3.0000000e+00, ..., 1.5169032e+02,
        5.3537760e+01, 1.8895680e+01]])

____________________________________________________________________
# Create Your Model
____________________________________________________________________

>## Supervised Learning Estimators

>>### Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression(normalize=True)

>>### Ridge regression

In [ ]:
from sklearn import linear_model

reg = linear_model.Ridge(alpha=.5)
reg.fit([[0, 0], [0, 0], [1, 1]], [0, .1, 1])

print(reg.coef_)
print(reg.intercept_)


[0.34545455 0.34545455]
0.13636363636363638


>>### Support Vector Machines (SVM)

In [ ]:
from sklearn.svm import SVC

svc = SVC(kernel='linear')

>>### Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

>>### KNN

In [ ]:
from sklearn import neighbors
knn = neighbors.KNeighborsClassifier(n_neighbors=5)

>## Unsupervised Learning Estimators

>>### Principal Component Analysis (PCA)

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=0.95)

>>### K Means

In [ ]:
from sklearn.cluster import KMeans
k_means = KMeans(n_clusters=3, random_state=0)

____________________________________________________________________
# Model Fitting
____________________________________________________________________

>### Supervised learning

In [ ]:
lr.fit(X, y)
knn.fit(X_train, y_train)
svc.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

>### Unsupervised Learning

In [ ]:
k_means.fit(X_train)
pca_model = pca.fit_transform(X_train)

____________________________________________________________________
# Prediction
____________________________________________________________________

>### Supervised Estimators

In [ ]:
y_pred = svc.predict(np.random.random((2,4)))
y_pred = lr.predict(X_test)
y_pred = knn.predict_proba(X_test)

>### Unsupervised Estimators

In [ ]:
y_pred = k_means.predict(X_test)

____________________________________________________________________
# Evaluate Your Model's Performance
____________________________________________________________________

>## Classification Metrics

>>### Accuracy Score

In [ ]:
knn.score(X_test, y_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.34210526315789475

>>### Classification Report

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         8
           1       0.00      0.00      0.00        11
           2       1.00      0.68      0.81        19

    accuracy                           0.34        38
   macro avg       0.33      0.23      0.27        38
weighted avg       0.50      0.34      0.41        38



>>### Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[ 0  8  0]
 [11  0  0]
 [ 6  0 13]]


>## Regression Metrics

>>### Mean Absolute Error

In [ ]:
from sklearn.metrics import mean_absolute_error
y_true = [3, -0.5, 2]
mean_absolute_error(y_true, y_pred)

ValueError: ignored

>>### Mean Squared Error

In [ ]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

>>### R2 Score

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_true, y_pred)

>## Clustering Metrics

>>### Adjusted Rand Index

In [ ]:
from sklearn.metrics import adjusted_rand_score
adjusted_rand_score(y_true, y_pred)

>>### Homogeneity

In [ ]:
from sklearn.metrics import homogeneity_score
homogeneity_score(y_true, y_pred)

>>### V-measure

In [ ]:
from sklearn.metrics import v_measure_score
metrics.v_measure_score(y_true, y_pred)

>>### Cross-Validation

In [ ]:
print(cross_val_score(knn, X_train, y_train, cv=4)
print(cross_val_score(lr, X, y, cv=2)

____________________________________________________________________
# Tune Your Model
___________________________________________________________________

>## Grid Search

In [ ]:
from sklearn.grid_search import GridSearchCV
params = {"n_neighbors": np.arange(1,3), "metric": ["euclidean", "cityblock"]}
grid = GridSearchCV(estimator=knn,param_grid=params)
grid.fit(X_train, y_train)
print(grid.best_score_)
print(grid.best_estimator_.n_neighbors)

>## Randomized Parameter Optimization

In [ ]:
from sklearn.grid_search import RandomizedSearchCV
params = {"n_neighbors": range(1,5), "weights": ["uniform", "distance"]}
rsearch = RandomizedSearchCV(
            estimator=knn,
            param_distributions=params,
            cv=4,
            n_iter=8,
            random_state=5)

rsearch.fit(X_train, y_train)
print(rsearch.best_score_)